CREATE TABLE chief_table (
  id INT NOT NULL AUTO_INCREMENT,
  FirstName VARCHAR(45) NULL,
  LastName VARCHAR(45) NULL,
  BirthDate Date NULL,
  Gender VARCHAR(45) NULL,
  Address VARCHAR(45) NULL,
  Contact INT NULL,
  FatherFirstName VARCHAR(45) NULL,
  FatherLastName VARCHAR(45) NULL,
  MotherFirstName VARCHAR(45) NULL,
  MotherLastName VARCHAR(45) NULL,
  SssNumber INT NULL,
  Tax VARCHAR(45) NULL,
  Position VARCHAR(100) NULL,
  UnitDivision VARCHAR(100) NULL,
  idNumbers VARCHAR(45) NULL,
  Password VARCHAR(45) NULL,
  ConfirmPassword VARCHAR(45) NULL,
  image MEDIUMBLOB NULL,
  Pagibig VARCHAR(45) NULL,
  Philhealth VARCHAR(45) NULL,
  Status VARCHAR(45) NULL,
  Emergency VARCHAR(45) NULL,
  EmergencyNumber VARCHAR(45) NULL,
  BloodType VARCHAR(45) NULL,
  Remarks VARCHAR (100) NULL,
  PRIMARY KEY (id));