INSERT INTO chief_table 
(
FirstName, LastName, BirthDate, Gender, Address, Contact, FatherFirstName,FatherLastName,MotherFirstName, MotherLastName, SssNumber, Tax,Position, UnitDivision, idNumbers, Password, ConfirmPassword, Pagibig, Philhealth, Status,Emergency,EmergencyNumber,BloodType, Remarks
)
VALUES
(
'john',
'doe',
'1996-05-05',
'Gender', 
'Address', 
'123', 
'FatherFirstName',
'FatherLastName',
'MotherFirstName', 
'MotherLastName', 
'123', 
'Tax',
'Position', 
'UnitDivision', 
'123', 
'123', 
'123',
'Pagibig num',
'philhealth code',
'active or retired',
'Emergency',
'EmergencyNumber',
'BloodType',
'date left and the reason'
),
(
'Shyra Mae',
'Eduardo',
'1996-05-05',
'Female', 
'Address', 
'123', 
'FatherFirstName',
'FatherLastName',
'MotherFirstName', 
'MotherLastName', 
'123', 
'Tax',
'Unit Officer I - ICTU MIS', 
'INFORMATION AND COMMUNICATION TECHNOLOGY - MANAGEMENT INFORMATION SYSTEM UNIT', 
'1911001', 
'123', 
'123',
'Pagibig num',
'philhealth code',
'active or retired',
'Emergency',
'EmergencyNumber',
'BloodType',
'date left and the reason'
),
(
'Christian ',
'Botalon',
'1996-05-05',
'Male', 
'Address', 
'123', 
'FatherFirstName',
'FatherLastName',
'MotherFirstName', 
'MotherLastName', 
'123', 
'Tax',
'Human Resource Management Aide', 
'HUMAN RESOURCE MANAGEMENT UNIT', 
'1909001', 
'123', 
'123',
'Pagibig num',
'philhealth code',
'active or retired',
'Emergency',
'EmergencyNumber',
'BloodType',
'date left and the reason'),
(
'Ellen ',
'Abellera',
'1996-05-05',
'Male', 
'Address', 
'123', 
'FatherFirstName',
'FatherLastName',
'MotherFirstName', 
'MotherLastName', 
'123', 
'Tax',
'Human Resource Management Aide', 
'HUMAN RESOURCE MANAGEMENT UNIT', 
'1801018', 
'123', 
'123',
'Pagibig num',
'philhealth code',
'active or retired',
'Emergency',
'EmergencyNumber',
'BloodType',
'date left and the reason'),
(
'Octavia ',
'Ablos',
'1996-05-05',
'Male', 
'Address', 
'123', 
'FatherFirstName',
'FatherLastName',
'MotherFirstName', 
'MotherLastName', 
'123', 
'Tax',
'Human Resource Management Aide', 
'HUMAN RESOURCE MANAGEMENT UNIT', 
'1507001', 
'123', 
'123',
'Pagibig num',
'philhealth code',
'active or retired',
'Emergency',
'EmergencyNumber',
'BloodType',
'date left and the reason')
,
(
'Geraldine ',
'Alican',
'1996-05-05',
'Male', 
'Address', 
'123', 
'FatherFirstName',
'FatherLastName',
'MotherFirstName', 
'MotherLastName', 
'123', 
'Tax',
'Human Resource Management Aide', 
'HUMAN RESOURCE MANAGEMENT UNIT', 
'1710006', 
'123', 
'123',
'Pagibig num',
'philhealth code',
'active or retired',
'Emergency',
'EmergencyNumber',
'BloodType',
'date left and the reason'),
(
'Arnold ',
'Anablon',
'1996-05-05',
'Male', 
'Address', 
'123', 
'FatherFirstName',
'FatherLastName',
'MotherFirstName', 
'MotherLastName', 
'123', 
'Tax',
'Human Resource Management Aide', 
'HUMAN RESOURCE MANAGEMENT UNIT', 
'1710002', 
'123', 
'123',
'Pagibig num',
'philhealth code',
'active or retired',
'Emergency',
'EmergencyNumber',
'BloodType',
'date left and the reason');